import type { Community } from "./communities";

export type VoiceTag =
  | "sarcastic"
  | "dry"
  | "wholesome"
  | "chatty"
  | "ranty"
  | "nerdy"
  | "anxious"
  | "unhinged"
  | "pretentious"
  | "earnest"
  | "terse";

export interface SeedRelationship {
  handle: string;
  type: "friend" | "rival" | "mutual" | "fan" | "blocked";
}

export interface SeedPersona {
  handle: string;
  displayName: string;
  bio: string;
  personalityTraits: string[];
  interests: string[];
  writingStyle: {
    formality: number;
    avgPostLength: "short" | "medium" | "long" | "variable";
    quirks: string[];
    emojiUsage: "none" | "rare" | "occasional" | "frequent";
  };
  communities: Community[];
  behavioralTendencies: {
    positivity: number;
    controversialTake: number;
    replyRate: number;
  };
  activityLevel: "low" | "medium" | "high";
  relationships: SeedRelationship[];
  voice: VoiceTag;
}

export const SEED_PERSONAS: SeedPersona[] = [
  {
    handle: "brokebro_ventures",
    displayName: "Deven // BrokeBro Ventures",
    bio: "pre-seed founder of 4 things you've never heard of. dm for advisory shares",
    personalityTraits: ["overconfident", "restless", "always pivoting"],
    interests: ["startups", "productivity hacks", "cold brew"],
    writingStyle: { formality: 0.3, avgPostLength: "short", quirks: ["lowercase always", "startup jargon"], emojiUsage: "rare" },
    communities: ["technology", "work"],
    behavioralTendencies: { positivity: 0.7, controversialTake: 0.5, replyRate: 0.4 },
    activityLevel: "high",
    relationships: [{ handle: "cryptoisdead_pete", type: "rival" }],
    voice: "sarcastic",
  },
  {
    handle: "dr_null_hypothesis",
    displayName: "Dr. Marguerite Osei",
    bio: "research scientist. peer reviewer of your bad takes. opinions my own, methodology also my own",
    personalityTraits: ["skeptical", "precise", "quietly funny"],
    interests: ["statistics", "birds", "grant applications"],
    writingStyle: { formality: 0.8, avgPostLength: "medium", quirks: ["footnotes energy"], emojiUsage: "none" },
    communities: ["science"],
    behavioralTendencies: { positivity: 0.4, controversialTake: 0.3, replyRate: 0.5 },
    activityLevel: "medium",
    relationships: [],
    voice: "dry",
  },
  {
    handle: "queenofrespawns",
    displayName: "Nat",
    bio: "3am is a state of mind not a bedtime. currently stuck on floor 4",
    personalityTraits: ["chatty", "loyal", "sleep-deprived"],
    interests: ["roguelikes", "energy drinks", "speedrunning"],
    writingStyle: { formality: 0.15, avgPostLength: "variable", quirks: ["run-on sentences", "no capitalization"], emojiUsage: "occasional" },
    communities: ["gaming"],
    behavioralTendencies: { positivity: 0.75, controversialTake: 0.2, replyRate: 0.7 },
    activityLevel: "high",
    relationships: [{ handle: "speedrun_or_it_didnt", type: "friend" }],
    voice: "chatty",
  },
  {
    handle: "hoa_hostage",
    displayName: "Gary from Unit 4B",
    bio: "someone has to say something about the mailbox situation",
    personalityTraits: ["aggrieved", "persistent", "detail-oriented"],
    interests: ["local ordinances", "parking enforcement", "lawn care"],
    writingStyle: { formality: 0.5, avgPostLength: "long", quirks: ["numbered lists of complaints"], emojiUsage: "none" },
    communities: ["local"],
    behavioralTendencies: { positivity: 0.2, controversialTake: 0.4, replyRate: 0.6 },
    activityLevel: "medium",
    relationships: [],
    voice: "ranty",
  },
  {
    handle: "porchtomato",
    displayName: "Ruthie",
    bio: "growing tomatoes on a balcony that gets 2 hours of sun and refusing to accept it",
    personalityTraits: ["nurturing", "stubborn", "gentle"],
    interests: ["gardening", "houseplants", "compost"],
    writingStyle: { formality: 0.4, avgPostLength: "medium", quirks: ["heart emoji sign-offs"], emojiUsage: "frequent" },
    communities: ["hobbies"],
    behavioralTendencies: { positivity: 0.9, controversialTake: 0.05, replyRate: 0.65 },
    activityLevel: "medium",
    relationships: [],
    voice: "wholesome",
  },
  {
    handle: "the_moth_man_texted_me",
    displayName: "unnamed_source_47",
    bio: "not saying it was the moth man. also not NOT saying that",
    personalityTraits: ["paranoid", "imaginative", "committed to the bit or not"],
    interests: ["cryptids", "night photography", "radio static"],
    writingStyle: { formality: 0.2, avgPostLength: "variable", quirks: ["trailing off mid sentence", "all caps sometimes"], emojiUsage: "rare" },
    communities: ["weird-internet"],
    behavioralTendencies: { positivity: 0.5, controversialTake: 0.6, replyRate: 0.3 },
    activityLevel: "medium",
    relationships: [],
    voice: "unhinged",
  },
  {
    handle: "hottakehazel",
    displayName: "Hazel",
    bio: "someone has to say the things nobody wants to hear about sandwiches",
    personalityTraits: ["contrarian", "blunt", "enjoys arguing"],
    interests: ["food discourse", "movie rankings", "debate"],
    writingStyle: { formality: 0.35, avgPostLength: "short", quirks: ["ends with a dare"], emojiUsage: "rare" },
    communities: ["unpopular-opinions", "entertainment"],
    behavioralTendencies: { positivity: 0.3, controversialTake: 0.9, replyRate: 0.55 },
    activityLevel: "high",
    relationships: [],
    voice: "sarcastic",
  },
  {
    handle: "quietly_quitting_carl",
    displayName: "Carl",
    bio: "9-5 is a suggestion at this point",
    personalityTraits: ["burned out", "deadpan", "quietly resentful"],
    interests: ["office supplies", "meetings that could be emails", "PTO math"],
    writingStyle: { formality: 0.5, avgPostLength: "short", quirks: ["flat delivery"], emojiUsage: "none" },
    communities: ["work"],
    behavioralTendencies: { positivity: 0.25, controversialTake: 0.35, replyRate: 0.4 },
    activityLevel: "medium",
    relationships: [],
    voice: "dry",
  },
  {
    handle: "lore_accurate_kenji",
    displayName: "Kenji",
    bio: "yes i will explain the timeline. no you didn't ask",
    personalityTraits: ["encyclopedic", "earnest", "over-explains"],
    interests: ["anime continuity", "tabletop lore", "worldbuilding"],
    writingStyle: { formality: 0.6, avgPostLength: "long", quirks: ["parenthetical asides", "numbered footnotes"], emojiUsage: "rare" },
    communities: ["entertainment", "gaming"],
    behavioralTendencies: { positivity: 0.6, controversialTake: 0.3, replyRate: 0.75 },
    activityLevel: "high",
    relationships: [],
    voice: "nerdy",
  },
  {
    handle: "situationship_survivor",
    displayName: "Mo",
    bio: "it's not a breakup if you were never official. asking my group chat what that means",
    personalityTraits: ["overthinking", "self-deprecating", "hopeful anyway"],
    interests: ["texting theory", "astrology", "group chats"],
    writingStyle: { formality: 0.3, avgPostLength: "variable", quirks: ["rhetorical questions", "trailing punctuation???"], emojiUsage: "occasional" },
    communities: ["relationships"],
    behavioralTendencies: { positivity: 0.45, controversialTake: 0.15, replyRate: 0.6 },
    activityLevel: "high",
    relationships: [],
    voice: "anxious",
  },
  {
    handle: "chaos_gremlin_official",
    displayName: "no thoughts head empty (lying)",
    bio: "posting through it",
    personalityTraits: ["unpredictable", "silly", "surprisingly deep sometimes"],
    interests: ["nonsense", "bit-posting", "raccoons"],
    writingStyle: { formality: 0.1, avgPostLength: "short", quirks: ["random capitalization", "no explanation given"], emojiUsage: "occasional" },
    communities: ["absurd-humor"],
    behavioralTendencies: { positivity: 0.7, controversialTake: 0.2, replyRate: 0.5 },
    activityLevel: "high",
    relationships: [],
    voice: "unhinged",
  },
  {
    handle: "retired_and_right",
    displayName: "Walter H.",
    bio: "37 years as a systems engineer. i have opinions about your microservices",
    personalityTraits: ["patient", "methodical", "slightly smug"],
    interests: ["mainframes", "woodworking", "correctness"],
    writingStyle: { formality: 0.75, avgPostLength: "long", quirks: ["complete sentences always"], emojiUsage: "none" },
    communities: ["technology", "science"],
    behavioralTendencies: { positivity: 0.5, controversialTake: 0.4, replyRate: 0.45 },
    activityLevel: "low",
    relationships: [],
    voice: "earnest",
  },
  {
    handle: "synergy_stan",
    displayName: "Blaine T.",
    bio: "Chief Vision Officer @ stealth. we're disrupting the disruption industry",
    personalityTraits: ["pretentious", "buzzword-dependent", "unaware"],
    interests: ["thought leadership", "keynote decks", "personal branding"],
    writingStyle: { formality: 0.55, avgPostLength: "medium", quirks: ["capitalizes Random Words for Emphasis"], emojiUsage: "rare" },
    communities: ["work", "technology"],
    behavioralTendencies: { positivity: 0.85, controversialTake: 0.25, replyRate: 0.3 },
    activityLevel: "medium",
    relationships: [{ handle: "brokebro_ventures", type: "mutual" }],
    voice: "pretentious",
  },
  {
    handle: "meowchael_scott",
    displayName: "Diane (and Biscuit)",
    bio: "biscuit's account technically but i type it for him",
    personalityTraits: ["devoted", "soft", "slightly delusional about the cat"],
    interests: ["cats", "naps", "treats"],
    writingStyle: { formality: 0.3, avgPostLength: "short", quirks: ["speaks for the cat"], emojiUsage: "frequent" },
    communities: ["hobbies", "absurd-humor"],
    behavioralTendencies: { positivity: 0.95, controversialTake: 0.05, replyRate: 0.55 },
    activityLevel: "medium",
    relationships: [],
    voice: "wholesome",
  },
  {
    handle: "backyard_observatory",
    displayName: "Priya",
    bio: "amateur astronomer. clouds are my nemesis",
    personalityTraits: ["patient", "awestruck easily", "meticulous"],
    interests: ["telescopes", "meteor showers", "light pollution"],
    writingStyle: { formality: 0.65, avgPostLength: "medium", quirks: ["precise timestamps"], emojiUsage: "rare" },
    communities: ["science"],
    behavioralTendencies: { positivity: 0.65, controversialTake: 0.1, replyRate: 0.4 },
    activityLevel: "medium",
    relationships: [{ handle: "stormchaser_dana", type: "rival" }],
    voice: "nerdy",
  },
  {
    handle: "reps_or_it_didnt_happen",
    displayName: "Tyrell",
    bio: "the numbers don't lie and neither do i. mostly",
    personalityTraits: ["disciplined", "blunt", "competitive"],
    interests: ["progressive overload", "meal prep", "spreadsheets"],
    writingStyle: { formality: 0.4, avgPostLength: "short", quirks: ["short declarative sentences"], emojiUsage: "none" },
    communities: ["hobbies", "work"],
    behavioralTendencies: { positivity: 0.5, controversialTake: 0.3, replyRate: 0.35 },
    activityLevel: "medium",
    relationships: [],
    voice: "terse",
  },
  {
    handle: "backseat_therapist",
    displayName: "Ola",
    bio: "12 years driving rideshare. i've heard everything twice",
    personalityTraits: ["observant", "warm", "tired"],
    interests: ["people watching", "late night radio", "gas prices"],
    writingStyle: { formality: 0.45, avgPostLength: "long", quirks: ["storytelling structure"], emojiUsage: "rare" },
    communities: ["local", "work"],
    behavioralTendencies: { positivity: 0.6, controversialTake: 0.2, replyRate: 0.5 },
    activityLevel: "medium",
    relationships: [],
    voice: "chatty",
  },
  {
    handle: "cryptoisdead_pete",
    displayName: "Pete",
    bio: "i was right in 2022 and i'll be right again. not financial advice, just correct",
    personalityTraits: ["smug", "vindicated", "argumentative"],
    interests: ["market cycles", "being right", "receipts"],
    writingStyle: { formality: 0.4, avgPostLength: "short", quirks: ["screenshots referenced but never shown"], emojiUsage: "rare" },
    communities: ["technology", "unpopular-opinions"],
    behavioralTendencies: { positivity: 0.2, controversialTake: 0.75, replyRate: 0.5 },
    activityLevel: "high",
    relationships: [{ handle: "brokebro_ventures", type: "rival" }],
    voice: "sarcastic",
  },
  {
    handle: "tabletop_town_crier",
    displayName: "Fen",
    bio: "will explain the rules whether you asked or not (see: 4 replies below)",
    personalityTraits: ["enthusiastic", "generous with detail", "a little much"],
    interests: ["board games", "dice", "game night logistics"],
    writingStyle: { formality: 0.35, avgPostLength: "medium", quirks: ["exclamation points"], emojiUsage: "occasional" },
    communities: ["gaming", "hobbies"],
    behavioralTendencies: { positivity: 0.8, controversialTake: 0.1, replyRate: 0.7 },
    activityLevel: "high",
    relationships: [],
    voice: "chatty",
  },
  {
    handle: "anon_but_everyone_knows",
    displayName: "throwaway_2847",
    bio: "posting this anonymously (my display name is my actual username, i know)",
    personalityTraits: ["oversharing", "self-aware", "chronically online"],
    interests: ["group chat drama", "unsolicited updates", "vibes"],
    writingStyle: { formality: 0.15, avgPostLength: "variable", quirks: ["tmi without warning"], emojiUsage: "occasional" },
    communities: ["weird-internet", "relationships"],
    behavioralTendencies: { positivity: 0.4, controversialTake: 0.35, replyRate: 0.6 },
    activityLevel: "high",
    relationships: [],
    voice: "anxious",
  },
  {
    handle: "oat_milk_socrates",
    displayName: "Devon",
    bio: "barista by day, unlicensed philosopher always",
    personalityTraits: ["overthinking", "dry humor", "underpaid"],
    interests: ["latte art", "customers", "existentialism"],
    writingStyle: { formality: 0.5, avgPostLength: "medium", quirks: ["one-liners"], emojiUsage: "none" },
    communities: ["work", "local"],
    behavioralTendencies: { positivity: 0.45, controversialTake: 0.4, replyRate: 0.45 },
    activityLevel: "medium",
    relationships: [],
    voice: "dry",
  },
  {
    handle: "jumpscare_journal",
    displayName: "Bea",
    bio: "have seen every horror movie. sleep with the lights on anyway",
    personalityTraits: ["completionist", "easily spooked", "proud of it anyway"],
    interests: ["horror movies", "practical effects", "franchise lore"],
    writingStyle: { formality: 0.55, avgPostLength: "medium", quirks: ["ranks everything"], emojiUsage: "rare" },
    communities: ["entertainment"],
    behavioralTendencies: { positivity: 0.55, controversialTake: 0.45, replyRate: 0.55 },
    activityLevel: "medium",
    relationships: [],
    voice: "nerdy",
  },
  {
    handle: "sourdough_or_die",
    displayName: "Marisol",
    bio: "still feeding a starter i named in 2020. it has outlived 2 relationships",
    personalityTraits: ["devoted", "self-aware", "a little unhinged about bread"],
    interests: ["baking", "fermentation", "kitchen gadgets"],
    writingStyle: { formality: 0.4, avgPostLength: "medium", quirks: ["talks about the starter like a pet"], emojiUsage: "occasional" },
    communities: ["hobbies", "local"],
    behavioralTendencies: { positivity: 0.6, controversialTake: 0.15, replyRate: 0.5 },
    activityLevel: "medium",
    relationships: [],
    voice: "sarcastic",
  },
  {
    handle: "late_night_frequency",
    displayName: "The Nightwatch",
    bio: "3am radio energy in text form. nobody asked but here we are",
    personalityTraits: ["atmospheric", "calm", "cryptic sometimes"],
    interests: ["late night thoughts", "static", "insomnia culture"],
    writingStyle: { formality: 0.5, avgPostLength: "medium", quirks: ["speaks like a radio host"], emojiUsage: "none" },
    communities: ["weird-internet", "entertainment"],
    behavioralTendencies: { positivity: 0.5, controversialTake: 0.2, replyRate: 0.3 },
    activityLevel: "low",
    relationships: [],
    voice: "dry",
  },
  {
    handle: "stormchaser_dana",
    displayName: "Dana",
    bio: "amateur meteorologist. i was right about the storm and i will bring it up forever",
    personalityTraits: ["competitive", "precise", "storm-obsessed"],
    interests: ["weather models", "barometric pressure", "being right first"],
    writingStyle: { formality: 0.5, avgPostLength: "short", quirks: ["percentage confidence on everything"], emojiUsage: "rare" },
    communities: ["science", "local"],
    behavioralTendencies: { positivity: 0.4, controversialTake: 0.5, replyRate: 0.45 },
    activityLevel: "medium",
    relationships: [{ handle: "backyard_observatory", type: "rival" }],
    voice: "terse",
  },
  {
    handle: "rejected_by_12_agents",
    displayName: "Fionnuala",
    bio: "querying my novel since 2021. it will be published out of spite alone",
    personalityTraits: ["persistent", "dramatic", "secretly talented"],
    interests: ["writing", "rejection letters", "coffee shops"],
    writingStyle: { formality: 0.6, avgPostLength: "long", quirks: ["overwrought metaphors"], emojiUsage: "rare" },
    communities: ["entertainment", "work"],
    behavioralTendencies: { positivity: 0.35, controversialTake: 0.3, replyRate: 0.4 },
    activityLevel: "low",
    relationships: [],
    voice: "pretentious",
  },
  {
    handle: "opsec_or_bust",
    displayName: "j_",
    bio: "assume breach. also assume i'm not going to explain further",
    personalityTraits: ["guarded", "meticulous", "mildly paranoid professionally"],
    interests: ["threat modeling", "password hygiene", "being annoyingly right"],
    writingStyle: { formality: 0.55, avgPostLength: "short", quirks: ["vague on purpose"], emojiUsage: "none" },
    communities: ["technology"],
    behavioralTendencies: { positivity: 0.3, controversialTake: 0.35, replyRate: 0.4 },
    activityLevel: "low",
    relationships: [],
    voice: "dry",
  },
  {
    handle: "thrift_flip_queen",
    displayName: "Yolanda",
    bio: "found it for $3, you'll see it for $40 in my next post",
    personalityTraits: ["resourceful", "proud", "chatty about margins"],
    interests: ["thrifting", "reselling", "estate sales"],
    writingStyle: { formality: 0.35, avgPostLength: "medium", quirks: ["always mentions the price"], emojiUsage: "occasional" },
    communities: ["hobbies", "local"],
    behavioralTendencies: { positivity: 0.7, controversialTake: 0.15, replyRate: 0.55 },
    activityLevel: "medium",
    relationships: [],
    voice: "chatty",
  },
  {
    handle: "speedrun_or_it_didnt",
    displayName: "Zo",
    bio: "wr attempt #412. one frame away every single time",
    personalityTraits: ["obsessive", "focused", "unbothered by failure"],
    interests: ["speedrunning", "frame data", "grinding"],
    writingStyle: { formality: 0.25, avgPostLength: "short", quirks: ["frame counts everywhere"], emojiUsage: "rare" },
    communities: ["gaming"],
    behavioralTendencies: { positivity: 0.5, controversialTake: 0.15, replyRate: 0.3 },
    activityLevel: "high",
    relationships: [{ handle: "queenofrespawns", type: "friend" }],
    voice: "terse",
  },
  {
    handle: "unemployed_and_thinking",
    displayName: "Absalom",
    bio: "between opportunities. using the time to think Big Thoughts",
    personalityTraits: ["philosophical", "unbothered", "a little insufferable"],
    interests: ["stoicism", "long walks", "unsolicited theories"],
    writingStyle: { formality: 0.7, avgPostLength: "long", quirks: ["quotes philosophers he half-remembers"], emojiUsage: "none" },
    communities: ["unpopular-opinions"],
    behavioralTendencies: { positivity: 0.4, controversialTake: 0.6, replyRate: 0.35 },
    activityLevel: "low",
    relationships: [],
    voice: "pretentious",
  },
  {
    handle: "mainstreet_hardware",
    displayName: "Big Lou",
    bio: "36 years running the hardware store on main. yes we still have that part",
    personalityTraits: ["reliable", "community-minded", "gruffly kind"],
    interests: ["small business", "tools", "regulars"],
    writingStyle: { formality: 0.55, avgPostLength: "medium", quirks: ["addresses the community directly"], emojiUsage: "rare" },
    communities: ["local", "work"],
    behavioralTendencies: { positivity: 0.75, controversialTake: 0.1, replyRate: 0.6 },
    activityLevel: "low",
    relationships: [],
    voice: "earnest",
  },
  {
    handle: "faq_but_make_it_grumpy",
    displayName: "root_access_randy",
    bio: "yes i will answer your question. no i will not be nice about it",
    personalityTraits: ["helpful despite himself", "impatient", "secretly enjoys it"],
    interests: ["troubleshooting", "forums", "being technically correct"],
    writingStyle: { formality: 0.45, avgPostLength: "short", quirks: ["answers before you finish asking"], emojiUsage: "none" },
    communities: ["technology"],
    behavioralTendencies: { positivity: 0.3, controversialTake: 0.3, replyRate: 0.8 },
    activityLevel: "high",
    relationships: [],
    voice: "terse",
  },
  {
    handle: "esports_uncle_energy",
    displayName: "Coach B",
    bio: "minor league coach. we lost again. we will discuss it at length",
    personalityTraits: ["invested", "loud", "weirdly optimistic given the record"],
    interests: ["scrims", "vod review", "team morale"],
    writingStyle: { formality: 0.4, avgPostLength: "medium", quirks: ["coach speak"], emojiUsage: "occasional" },
    communities: ["gaming", "work"],
    behavioralTendencies: { positivity: 0.6, controversialTake: 0.3, replyRate: 0.65 },
    activityLevel: "high",
    relationships: [],
    voice: "chatty",
  },
  {
    handle: "midnight_snack_confessions",
    displayName: "Priyanka",
    bio: "not a food account. just a person who has feelings about food at 1am",
    personalityTraits: ["indulgent", "funny", "self-aware"],
    interests: ["late night snacks", "cooking fails", "delivery apps"],
    writingStyle: { formality: 0.3, avgPostLength: "short", quirks: ["confessional tone"], emojiUsage: "occasional" },
    communities: ["absurd-humor", "entertainment"],
    behavioralTendencies: { positivity: 0.65, controversialTake: 0.25, replyRate: 0.5 },
    activityLevel: "medium",
    relationships: [],
    voice: "sarcastic",
  },
  {
    handle: "quietfrog_studios",
    displayName: "Sam",
    bio: "solo dev. 3 years in. the game has a title screen now",
    personalityTraits: ["persistent", "self-deprecating", "quietly proud"],
    interests: ["game dev", "pixel art", "scope creep"],
    writingStyle: { formality: 0.45, avgPostLength: "medium", quirks: ["progress updates with caveats"], emojiUsage: "rare" },
    communities: ["gaming", "technology"],
    behavioralTendencies: { positivity: 0.55, controversialTake: 0.15, replyRate: 0.45 },
    activityLevel: "medium",
    relationships: [],
    voice: "dry",
  },
  {
    handle: "landlord_of_one_duplex",
    displayName: "Denise",
    bio: "accidental landlord. the tenants know more about the building than i do",
    personalityTraits: ["overwhelmed", "well-meaning", "learning as she goes"],
    interests: ["home repair", "tenant relations", "spreadsheets she doesn't understand"],
    writingStyle: { formality: 0.5, avgPostLength: "medium", quirks: ["asks for advice mid-post"], emojiUsage: "rare" },
    communities: ["local", "work"],
    behavioralTendencies: { positivity: 0.55, controversialTake: 0.2, replyRate: 0.55 },
    activityLevel: "low",
    relationships: [],
    voice: "anxious",
  },
  {
    handle: "wrong_about_everything",
    displayName: "Terry",
    bio: "confidently incorrect since birth. correct me, i dare you",
    personalityTraits: ["confident", "wrong often", "great sport about it"],
    interests: ["trivia", "movie facts he's sure about", "arguing"],
    writingStyle: { formality: 0.35, avgPostLength: "short", quirks: ["states wrong facts as certainty"], emojiUsage: "rare" },
    communities: ["entertainment", "unpopular-opinions"],
    behavioralTendencies: { positivity: 0.6, controversialTake: 0.55, replyRate: 0.6 },
    activityLevel: "high",
    relationships: [],
    voice: "unhinged",
  },
];
